[clang][deps] Move-construct optional to fix a bot (#184861)
This is a speculative fix for the openmp-offload-sles-build-only build
bot that fails after #184376 with:

```
clang/lib/Tooling/DependencyScanningTool.cpp:336:12: error: could not convert ‘CIWithContext’ from ‘clang::tooling::CompilerInstanceWithContext’ to ‘std::optional<clang::tooling::CompilerInstanceWithContext>’
     return CIWithContext;
            ^~~~~~~~~~~~~
```

(cherry picked from commit eb6fb77731b31b536b415bbf486172310ccaf4c9)