[CIR][CodeGen] Implement VisitImplicitValueInitExpr in CIRGenExprScalar.cpp (#182256)
MRE:
```cpp
#include <vector>

std::vector<int> V;
```
```shell
$ ./bin/clang++ -fclangir -c test.cpp
error: ClangIR code gen Not Yet Implemented: ScalarExprEmitter: implicit value init
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
....
```
This PR fixes the crash by upstreaming:

https://github.com/llvm/clangir/blob/c1e076e803a04862443fa2ede13c35144fa79268/clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp#L397-L399
(cherry picked from commit 08b0f39dcf1ad764896ff776004328e8ae45f390)