[lldb] Mark lldbtest.build() parameters as keyword-only (#188327)
This reinforces what is already true in the codebase: all uses of
`build()` use keyword arguments.

With this change, it will be an error to call `build` using positional
arguments:

```
TypeError: build() takes 1 positional argument but 2 were given
```

(cherry picked from commit 2975451a70fbd4b35cc790294ee7ed46970a253b)