[NFC][IR] Fix MSVC C4706 diagnostic w/ 741b2cda32e1 (#182682)
Fix error:

llvm\include\llvm\IR\Operator.h(279) : error C2220: the following
warning is treated as an error
llvm\include\llvm\IR\Operator.h(279) : warning C4706: assignment within
conditional expression

(cherry picked from commit 372c65d7a3d20e74a960f1265136ddb5d3fc0bf6)