[CMake][MSVC] Add /Zi to release flags (#182515)
Try to fix MSVC error C2859, which complains about an outdated PDB file.
CMake appears to copy the PDB file for this reason, but it only looks in
one specific place for the /Zi flag.

(cherry picked from commit 5e5e082aebccd20761fe5879cae62135e4d5608d)