Fix build break with BUILD_SHARED_LIBS=ON
/usr/bin/ld: tools/mlir/lib/Conversion/VectorToXeGPU/CMakeFiles/obj.MLIR
VectorToXeGPU.dir/VectorToXeGPU.cpp.o: in function `(anonymous namespace
)::ConvertVectorToXeGPUPass::runOnOperation()':
VectorToXeGPU.cpp:(.text._ZN12_GLOBAL__N_124ConvertVectorToXeGPUPass14ru
nOnOperationEv+0xbc): undefined reference to `mlir::populatePrepareVecto
rToMMAPatterns(mlir::RewritePatternSet&, bool)'
clang++: error: linker command failed with exit code 1 (use -v to see in
vocation)

(cherry picked from commit e5e709adeec3c5c063fc756d077a9b53dc469eb2)