[Vectorize] Silence a warning (NFC)
/llvm-project/llvm/lib/Transforms/Vectorize/VPlanConstruction.cpp:1533:11:
 error: unused variable 'FindIVSelect' [-Werror,-Wunused-variable]
    auto *FindIVSelect = findUserOf<Instruction::Select>(FindIVCmp);
          ^
1 error generated.

(cherry picked from commit f53fe860385c706903f74ac45404e95a841c113f)