[TableGen] Silence a warning (NFC)
llvm-project/llvm/utils/TableGen/DAGISelMatcherOpt.cpp:495:16:
 error: unused variable 'Tmp' [-Werror,-Wunused-variable]
      Matcher *Tmp =
               ^
1 error generated.

(cherry picked from commit 241b8876ddc7c8805cd0ab4f8265842c0782023e)